Traceback (most recent call last):
  File "main.py", line 17, in <module>
    wandb.run.name = now
  File "C:\Users\pc03\anaconda3\envs\pokemon\lib\site-packages\wandb\sdk\wandb_run.py", line 779, in __setattr__
    super().__setattr__(attr, value)
  File "C:\Users\pc03\anaconda3\envs\pokemon\lib\site-packages\wandb\sdk\wandb_run.py", line 371, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\pc03\anaconda3\envs\pokemon\lib\site-packages\wandb\sdk\wandb_run.py", line 931, in name
    self._backend.interface.publish_run(self)
  File "C:\Users\pc03\anaconda3\envs\pokemon\lib\site-packages\wandb\sdk\interface\interface.py", line 146, in publish_run
    run_record = self._make_run(run)
  File "C:\Users\pc03\anaconda3\envs\pokemon\lib\site-packages\wandb\sdk\interface\interface.py", line 135, in _make_run
    run._make_proto_run(proto_run)
  File "C:\Users\pc03\anaconda3\envs\pokemon\lib\site-packages\wandb\sdk\wandb_run.py", line 816, in _make_proto_run
    run.display_name = self._name
TypeError: bad argument type for built-in operation